name: Build and Deploy your Docker Image to Docker Hub

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install packages in the e2e-tests
        working-directory: e2e-tests
        run: npm i

      # Start the backend and frontend before running E2E tests
      - name: Start backend
        working-directory: backend
        run: npm start & # Start backend in the background

      - name: Start frontend
        working-directory: frontend
        run: npm start & # Start frontend in the background

      # Wait for the servers to start
      - name: Wait for services to be ready
        run: npx wait-on http://localhost:3000

      # Run E2E tests
      - name: Run E2E tests
        working-directory: e2e-tests
        run: npm test

      - name: Docker Hub Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Build the Docker image
        run: | # docker-compose build -t ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_IMAGE_NAME }}:latest -f ./frontend/Dockerfile ./frontend
          docker-compose build

      - name: Push Docker image to Docker Hub for the Frontend
        run: |
          docker-compose push frontend

      - name: Push Docker image to Docker Hub for the Backend
        run: |
          docker-compose push backend
